- project:
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - stx-root-upload-git-mirror

- job:
    name: stx-root-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/root to
      github.com/starlingx/root
    vars:
      git_mirror_repository: starlingx/root
    secrets:
      - name: git_mirror_credentials
        secret: stx-root-github-secret3
        pass-to-parent: true

- secret:
    name: stx-root-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - TD2KKt2Y27T8rAGeZYbyKdeFb8IAug17noqBBYRDA1Y4c6buaJK57LOVx82Q2Ki8bp9eR
          XbN6Eahh20cOjctU6PWjoDcvImWlttU96Pl1kkOEhTA1Wogwr7YsTy0owyyfpAy1fXqow
          ozigZ3mXpSLt5RaDHN5GsNvRI1T9rY8PRraZfMBq03ShW85HlYpOdbkIoWQIW4dGIp2Fc
          D5QBleAHJYKs8g4eiMdvk+uj45GlqQUjG7WbODHt61UL7g4/W1RU6E7h897V7quL6VSJU
          eldd4gGni2NbxPhOHhzDbMtqhzXo26xWSva7i0ABheUXzhgGX7oWYlJy53psWa1/w/c37
          bhHFwRJQQxS9uUXP7lHIQJ7A2FFMOdXFxWD2adgGOaDedpOWVzWSAwwL6rIWDC8rFFq8X
          leEF/r4MjJJMMgCHerr7tPrQBWf4GsqyLh+3BrAb1TLMWz7fvBfyHt0cGvGZJtD1TKEIB
          d/a9mFxnHRQOBTMzoET5iT4iBA19FxqRGOvYg67sHXkpCdidPJJS1n7Gy7KHqq7/nBinp
          rn2pgpQliZHKWBpE/qD0qG75l95sFn+ppJwklHw5Djn4CWtkWhI+bkuOcwbelvAxUtdnk
          XX1stP/r+Iq1leX9oPtkevAYO++rUCb5k18KGpy5pVOope6GZAg9XK7EJcg63g=
        - HeqkiU57lMBF0fJ3Hi0nT47ppJoT5/7DETqWF3JdJTpa0vYbimzbfcLETq7hwOgqvVIi+
          qOYwT9f2HJsIPp3VkY5x2vdusYpvBvi/JpDp8z0cBWs0xAEwLpqZWF03EmqyHRZI9KmJq
          QlOFa7nHDRsPGP8+eDiMF8Olx1QSReAMTg50PMc8Cv3AEsPoy8JPX7rEkEoGBVtLbmfhT
          3YCSqQxN4lohJbQD1sAZFelhS+1CywbvwB3F182bcPWJA0MHQKS68OESxok2P7cxQZJqR
          z2UFcnZHztKtronTZ22AmLo1N9x+AVx1GXsEkj6XJuOx5eDOvjf/4n1JL0BhDsyuNHVFZ
          DqlNZzGbP49wxTCgNUQlgeWSoHA7N7Y1L6reOYfPKQ10amPPLSs8Om+BkQStUTTCFcqG3
          tUfHmAX20nhNN0mgtXBvRZsyeu8BgTM8xQg4TCteaM6Oteh9TVdW1NN+xVrg2z5x8dGfl
          Z/EMSikQCg8MULXnoyvYMREbsmfUCzSXzHBNZSjExntX+E8cwVY5EvlHqvo+eW+8nywaO
          /+qkmD4fPETWJtXXLPNllRwjz7Z8UIxiMWkxGGnkuLf5OfO/ZYJdloPAI4S5FxvRYQ7Tx
          Ufep0I/PXfcfYwgyRe7myNdv7e9W2rZUJ7QsFXUgggsVJw5MnyOQDQCLx6Igf4=
        - RZ/1BApsbp5bk1z5JKlr1DRocHjHIJW5fRWehP5YBZ6TcyHtCI4wiS7vZ/LUXAzzIrGQi
          tgH+V5BjyIphb9hTgaC178mZTR0soFE1NMXWqiFuBVGDI1kyiAMNH6/qMs0cMnlLycX3S
          C1gBBMXVpZaGr6HRZr7hFjUFl9vuWr2eo1vpNEmkD5fKy4a3Wnk7vaENcbo/8atPBsQyf
          joERB7QFweV3bR5zAVcjRn21/iLs4i2oy41YtHFFNkbXvLnRYeQeCgj9i1VdPwGT2O/nh
          HPab/zZV6HB31ksZuOWth8EIdqvLyc6JebyhHZ8CElFwcRYWuOv84NfHxA7mWNqfnMJba
          K6zxLb3E++PiGAl7JgHZ9uYmAmt44DO7glfCeFt4+Qxe8TPIg2197UsI+TYlW04GUyMfK
          haUPwZ2EgBSu4oTA0KW2sOMCf63Q/pvcbvV6q2AN5kf/DNgUJ8A2VUAZEtJiidvRCidSK
          u7tPcBS3OqK36HyZbUy94Fw+y+CcPqtVButMXbOKAkO3Vc7j5UusVz6Gf2dCkdf8sgKxj
          vOK3URr0oTq3rMZIHo+rICA8CCg4WOXTeJWnxs+bGsdEXCnxGb0dkgQFVJnSHQkFVG3RQ
          0y7thaJIfZA4KMHltIr57vdvJGB+SGk7xQmxn/f402YoFg0mUZwpwjcycym0YU=
        - JfPQVOZk+IWR8q28M12fYQKAaBFbxGCfuMMYFDO2b/HZjETfOl2puQkZ6o+lXBsqjRlti
          Nixt+lrM0lzEM3pv+ge3/jCFroXA1ealkcUY3zJBnZ/aDXO3TQxpcKp0mP7pwxW7IXRPg
          9YyqCI368BcFbUrdKrKeLTZkonFu3MhjskMvkD8DFcaaQgC3GCLGkwRAazwk8iWQbz2C9
          n+vj8Suv1x7v3kew1TYYQPKa5dBuQ/qvkq3ass0jo75vh2beWZk+JgdtrdqAGR1IKyXEz
          2iyjEmprjqJupggUoYShFiTKK1IPSLnzDp5f5DSHZYJ1vQ+3g7oBerCtJhZw6nS/bMQIU
          HtOvUOytGCPVsJz4kLcFAtBIitEZ/RRq8Lad9Ek9puHAC/UBSXNeSXFuDBsnN829ypWlQ
          2S0k2LoVmTxcYYLuqDOW49e7f3JVdJ8PdDc2YpSBWOhIpdpCJ4F3vuOfcgmaZw8Jg970N
          fKK2vBdLOcGH044cLFcu4nyNZ9aU+h2WtsLkgXu5RZCrpBtUM/ipx/Q2BpDhxpyO08LAb
          zGC1e/WK4+Cbaxdfyr7yATC0Th2VQ3sqsCwH8YCf1cgqWumeYDMjgX7mdXE60Fw9m3LDy
          JCEfmUGa9an9+ZTwRIHnGjG0RAa5ZQpfi9ye+06dutnxfO2P6CxZ5qLIxYBP/U=
        - ELSbRPI+dGPWSgVzfywdPd5QZlxrr9ig8fmiiJUPwC9OHFjTKfTqRejz6KZaQivxZS3gO
          C5G//CwI5z+ADO5cR17SWPg273j4AkjCfWGqLeJrq67BG4snDC5bo1tsm6PDCApK0Up8b
          jdVlBu439areLtjhb+N5yvtfZFALJYTPOZ7+/1zSfQp/XJUv22P9sQpVp4TT3neDspWQt
          xNzuYx25Uk/rBm7LF19X97BRVy5+KBYvSTY0FkMfAGJ3t0TEQbabDhXUaxnnMiaiGxCeJ
          73wFn+/KQlP2hiI3/2c293GO2BZObRF/M2Qse49iJw98rmIRvVqVbnqwYx8T+cvyuxwyG
          zjAKfBhX4EeU5de4fvOdXU0rpJOfkSwcLwwHAmYPLksYzS6wAI7EhDlVgB17AeAlCV1Ah
          EbkeLekzvgzQ+DYDTUsDvzJU7si7Kx5+ZWgwEPwwFUZ6soARLvktb/Q0xSK7JHQOvMI8A
          wMXHTLW8zcPWH+/i2qwdT0Nn7GDb1ZfYulkCGVKXmNtIjsJgm8Xv/QAR7QFEEkXH7IoM+
          xiJxgDWC/QAvCudTJFvCJ8aFuVWEw9ejkhjIWZX2n/TmFw4daEtLTH1SeIaJZ3JuOXKE/
          TZwslIhgCt7CaCi50eMZC2HJXX61QdSAbVm14ONW/HStlqhTUenPAtrCAQEN0Y=
        - Sh5+P7aw/iSVNd+x3dFst6/QjgIxjElIMFq+bTlhY1EYdWE7pI2cQwe4ZoE20klCfhDCK
          mMrWxjVWlODoC3TAXwXvchTAxmgUx78BR2cdLXlOkb8CCaR9ApbNjqwe1vILKWfrgXnvP
          cwjAJuRsMWHmlSL9HgfHXBFqqjgcvRJhunvuL8R2D5pOGsOxdDBKIE5i+QHb5KfOHFtOd
          BsJMpWI2jZGWuK8iJHv/m0ZKxv/DZlj3SkxorS8TOq4A5uQLt94a3cPX8fahZWUxZH5z3
          CnmxJMBxVqnZCSW2Ljm0G90RRcFRKCulE/PbY4ps0cnRlYvt6hIeLI304QReRFEkO6kSz
          6rzWgH4lFqS3sECZDtO3AHlHioPpVTwfjQAO8RTwaxqUSPkp5OUywlHZPamzkxslSc9j+
          PBZp70HvYFwKj9Za7XWeN/Bc2M4l2r4WzAvS8yu4jufZCIYAMAJRkExmfmXkkwHPiOY9V
          W5qtM/NfeTOlXdq40Yp+lg1AIovuZwC8w414+hX+ftHxwJOSKV0NLHGegZ/GAtw3t4Crp
          q01dBBsG7d0HPPOsrS4v5vAUKA3h2bM0M5MKay3ZvzAdtTSqzip+KOQq2n/kU/UPmT313
          uQVID5c9yrg/DYpOzZYTGEaKm93xI4N7F1KO1KHCFTugPlOMseGlO1Whb4eTvk=
        - ObCvnc3fbRxzM9ti5dgmuCEdYbnd1ndPHL9WlFzlWsxFvq9ok/shwjNM/u7KD4BkLiWZy
          O58KaRgRU0RG7rtO9maO78mKbYjx62x64yJ/86hVxWMDQyts3EFu1rFw0OkAqyXVrkILu
          gnyR5gwlaL9mrOz+uh1534mxy4848y8LOYAkvObhZCm+qDN7zMZXPzIkgnsfUmtVh0KPl
          7RJQWfEWpucLJPbeGlOI92mWskuEcpNNj3Pa5AKQ/25QlhhJ9d38mcQ41cSPaPIXWGra4
          9RSmDWHokAX3A/s0b8jnlzFy6yAx7U6kXPIvxHiTi9yZ9H0yg6lA/M0wv4v0yDsFDnnp+
          RuUaiQdR4+xNe42xkojDQTKiWx17CK14Qxx75WWyiZp6iCnBnJ0p0upSAcg2LC0YXedNY
          hp6G8KzslAao9yAwGyQEpwrtmiLGGSXj+uiAUxxPVnqe/nizCZs7H3ExPmPrOT598PQTk
          sKAKs2pBbM+4Cxpm4hhsSfr3X9OZ2c+Fx/Fm6OsSTBJgq9HUZ9/VXmzcBZJX/GBl2dU6U
          Yg03QC9yrVl5P9Zy7F2Imu56hBzykQYCDYx+hNOrjlKJTxZNXzyhRn35bCGAC+a3ufOIS
          8WsiDEH6+Wljlp9jWl1eK+/ih2Pa4L03/1QXSAPIdvtR+/g9MJMUSN3yPyGIm4=
