# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#
acpid
gdb
influxdb
#python3-influxdb
#python3-gunicorn
iperf3
isomd5sum
#python3-aodhclient
#python2-oslo-log
python3-six
#python3-d2to1
#hiera
#python3-pecan
#python3-configobj
#python3-pep8
#python2-rsa
#ruby-shadow
swig
syslinux
iotop
linuxptp
procps-ng
#python-daemon
python3-pyudev
curl
lvm2
time
postgresql
postgresql-server
postgresql-contrib
targetcli
strace
wget
bind-utils
selinux-policy
#pm-utils
tcpdump
sysstat
smartmontools
#collectd
#puppet-collectd
socat
attr

# for realtime kernel
#rtctl
#rt-setup

# For low-latency compute
#OVMF
edk2-ovmf

# neutron bgp
#python2-pankoclient

# ima plugin for RPM
ntfs-3g
ntfsprogs
#python-memcached
python3-coverage

# kubernetes packages
#docker-ce
#etcd
#docker-forward-journald

# Add debugging tools
zip
unzip
traceroute

# support for persistent sessions
#screen

# For kata container
#kata-runtime
