# Expected build arguments:
#   RELEASE: centos release
#
ARG RELEASE=7.5.1804
FROM centos:${RELEASE}

RUN set -ex ;\
    sed -i '/\[main\]/ atimeout=120' /etc/yum.conf ;\
    yum install --disablerepo=* ${REPO_OPTS} -y \
        yum-priorities ;\
    yum install -y centos-release-openstack-stein ;\
    rm -rf \
        /var/log/* \
        /tmp/* \
        /var/tmp/*

# root CA cert expired on October 1st, 2021
RUN yum update -y ca-certificates
