<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="patch_recipe">
    <xs:complexType>
      <xs:all>
        <xs:element name="sw_version" type="xs:string"/>
        <xs:element name="component" type="xs:string"/>
        <xs:element name="summary" type="xs:string" minOccurs="0"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
        <xs:element name="install_instructions" type="xs:string" minOccurs="0"/>
        <xs:element name="warnings" type="xs:string" minOccurs="0"/>
        <xs:element name="status" type="xs:string" minOccurs="0"/>
        <xs:element name="requires" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="extra_content" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="stx_source_packages" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pkg" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="third_party_packages" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pkg" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="stx_packages" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="package" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="binary_packages" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="package" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>