#!/usr/bin/env python3
#
# Copyright (c) 2023-2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
'''
Builds a StarlingX system patch
'''

import click
import logging
import os
import subprocess
import sys
import tarfile
import tempfile

import constants
from fetch_debs import FetchDebs
from apt_utils import get_apt_fetcher
import metadata
import metapackages
import signing.patch_signing as signing

sys.path.append('..')
import utils


# Default patch output directory
DEFAULT_PATCH_OUTPUT_DIR = os.path.join(constants.DEPLOY_ROOT, "patch_output")

# Metapackage dependency policy options
FILL = "fill"
VALIDATE = "validate"
DEPENDENCY_POLICY_OPTIONS = [FILL, VALIDATE]


logger = logging.getLogger('patch_builder')
utils.set_logger(logger)


class PatchBuilder(object):

    def __init__(self,
                 patch_recipe_file,
                 file_name=None,
                 sign_remote=False,
                 dependency_policy=None):

        self.metadata = metadata.PatchMetadata(patch_recipe_file)

        self.patch_name = file_name or f'{self.metadata.id}.patch'

        self.sign_remote = sign_remote

        # TODO: Move signing variables to constants module
        self.signing_server = os.environ.get('SIGNING_SERVER')
        self.signing_user = os.environ.get('SIGNING_USER')

        self.dependency_policy = dependency_policy

        self.apt_fetcher = get_apt_fetcher()

        self.validate_inputs()


    def validate_inputs(self):
        """Raise errors if any input is invalid"""

        # Formal signature requested without providing auths for signing server
        if self.sign_remote and \
           (self.signing_server == None or self.signing_user == None):
            msg = "Cannot sign patch without signing server info"
            logger.error(msg)
            raise Exception(msg)


    def download_binaries(self):
        """
        Process package lists in the patch recipe and download the
        required deb files from the local aptly repo into the temp build
        directory.

        - third_party_packages: Pull each third-party binary;
        - stx_source_packages: For each source STX package,
          identify the corresponding binaries and pull them;

        In addition, download corresponding metapackage binaries
        and edit them if necessary.
        """
        logger.debug("Fetching debs...")

        deb_fetcher = FetchDebs(
            apt_fetcher = self.apt_fetcher,
            stx_source_packages = self.metadata.stx_source_packages,
            third_party_packages = self.metadata.third_party_packages,
        )

        deb_fetcher.identify_stx_packages()
        deb_fetcher.identify_third_party_packages()

        self.metadata.metapackages = deb_fetcher.identify_metapackages()

        deb_fetcher.download()


    def apply_metapackage_policy(self):
        """
        Edit metapackage debs, handling metapackage version and the versions
        of its dependencies.
        Either:
        - Validate only (No changes. Throw error if any dependency doesn't have a fixed version)
        - Fill in versions only for packages included in patch
        - Fill in all missing dependency versions

        Any option other than validation will also update the metapackage version to match the patch.
        """

        deb_dir = self.apt_fetcher.binary_downloads_dir

        deb_basenames = [item for item in os.listdir(deb_dir)
            if os.path.isfile(os.path.join(deb_dir, item))
            and item.endswith(".deb")]

        package_names = [item.split('_',1)[0] for item in deb_basenames]

        metapackage_deb_paths = [os.path.join(deb_dir, item)
            for item in deb_basenames
            if item.startswith(constants.METAPACKAGE_NAME_PREFIX)]

        # Metapackage dependency policy.
        # Whether to fill in missing requirements or just validate original ones.

        # Default policy: Fill in versions only of packages being included in patch
        target_dependencies = package_names

        if self.dependency_policy == VALIDATE:

            # TODO: Implement validation to check that all metapackage dependencies
            #       are already set in the original metapackage debs.
            #       It also needs to check the metapackage version.
            raise NotImplementedError("Metapackage validation feature is pending")

        if self.dependency_policy == FILL:
            # Strict policy: Fill in version requirements for ALL metapackage dependencies
            target_dependencies = None

        for metapackage_deb_path in metapackage_deb_paths:
            metapackages.edit_metapackage(
                apt_fetcher=self.apt_fetcher,
                metapackage_deb_path=metapackage_deb_path,
                target_dependencies=target_dependencies,
                target_version=self.metadata.sw_version)


    def build_patch(self):
        logger.info(f"Patch name: {self.patch_name}")

        logger.info("Building patch...")

        with tempfile.TemporaryDirectory(prefix="patch_") as tmpdir:
            # TODO: Change paths used to absolute paths so we don't change the current directory
            #       Changing curdir in scripts tends to create weird bugs.
            os.chdir(tmpdir)

            # TODO: The FetchDebs class leaves behind a directory with its cache files
            #       and the download directories. Since that's not used for anything else,
            #       it should be removed after the patch is built.
            self.download_binaries()

            # Edit metapackage debs
            self.apply_metapackage_policy()

            # software tarball
            with tarfile.open("software.tar", "w") as software_tar:
                for binary_pkg in sorted(os.listdir(self.apt_fetcher.binary_downloads_dir)):
                    logger.info(f"Adding to software.tar: {binary_pkg}")
                    software_tar.add(os.path.join(self.apt_fetcher.binary_downloads_dir, binary_pkg), arcname=binary_pkg)
                    # append deb name into metadata
                    self.metadata.debs.append(binary_pkg)

            # Extra content
            if self.metadata.extra_content:
                logger.info("Adding in extra content...")
                with tarfile.open("extra.tar", "w") as extra_tar:
                    for item in self.metadata.extra_content:
                        logger.info(f"Adding: {item}")
                        extra_tar.add(item, arcname=os.path.join("extra", os.path.basename(item)))

            # Generate metadata.xml
            logger.debug("Generating metadata file")
            self.metadata.generate_patch_metadata("metadata.xml")
            with tarfile.open("metadata.tar", "w") as metadata_tar:
                metadata_tar.add("metadata.xml")

            os.remove("metadata.xml")

            signing.generate_md5_signature(tmpdir)
            signing.generate_detached_signature(tmpdir)

            patch_full_path = self.build_patch_file()

        if self.sign_remote:
            signing.sign_patch_remotely(patch_full_path, self.signing_server, self.signing_user)


    def build_patch_file(self):

        # Save files into .patch
        files = [f for f in os.listdir('.') if os.path.isfile(f)]

        if not os.path.exists(DEFAULT_PATCH_OUTPUT_DIR):
            os.makedirs(DEFAULT_PATCH_OUTPUT_DIR)

        patch_full_path = os.path.join(DEFAULT_PATCH_OUTPUT_DIR, self.patch_name)

        with tarfile.open(patch_full_path, "w:gz") as patch_tar:
            for item in files:
                logger.info(f"Adding to {self.patch_name}: {item}")
                patch_tar.add(item)

        logger.info(f"Patch file created {patch_full_path}")

        return patch_full_path


# TODO: Replace the --remote-sign flag for the patch recipe STATUS field.
# REL means to do the remote signature.


@click.command()
@click.option(
            '--recipe',
            help='Patch recipe input XML file, examples are available under EXAMPLES directory',
            required=True)
@click.option(
            '--name',
            help='Allow user to define name of the patch file. e.g.: test-sample-rr.patch. \
                Name will default to patch_id if not defined',
            required=False)
@click.option(
            '--remote-sign',
            help='Send the patch to defined SIGNING SERVER to be sign with an different key.',
            is_flag=True,
            required=False)
@click.option(
            '--dependency_policy',
            help="Metapackage dependencies policy. " \
                 "The default behavior is to set fixed version requirements only for packages included in the patch. " \
                 f"You may set '{FILL}' to fill in all missing dependency versions or " \
                 f"'{VALIDATE}' to check if all dependency versions are already previously set and fail otherwise." \
                 f"Note any option other than '{VALIDATE}' will also update the metapackage version to match the patch's 'sw_version'",
            type=click.Choice(DEPENDENCY_POLICY_OPTIONS),
            required=False,
            default=None)
def build(recipe, name=None, remote_sign=False, dependency_policy=None):
    try:
        patch_builder = PatchBuilder(recipe, name, remote_sign, dependency_policy)
        patch_builder.build_patch()

    except Exception as e:
        logger.exception(e)
        sys.exit(1)


if __name__ == '__main__':

    # 'click' decorator handles function parameters
    build() # pylint: disable=no-value-for-parameter
